### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by jbenet** [StyXman/ayrton#16]
just recently i wanted something like this.

the python syntax + piping alone is worth the switch. 

I'm curious how robust it is nowaddays. I see development has slowed down-- but that might just mean it's done ;)

**Comment by StyXman** [comment]
Well, so far I hadn't much opportunity to test it on the field; mostly personal scripts. And yes, development is, let's say, jittery, because I juggle several projects into my little spare time, including finding a new job :) 
But right now I'm expanding a little the unit tests, so I have better command detection (after all `foo[3].bar` *is* a valid command name), so it means I'm defining the semantics of using a name that does not exists (should I raise NameError or CommandnotFound?).
So keep an eye open, I should be doing another release soon-ish.
